In [38]:
import pandas as pd

In [39]:
# Read the dataset
from sqlalchemy import create_engine
con = create_engine("mysql+pymysql://root:12345@localhost/july")
df = pd.read_sql("select * from synthetic_healthcare",con = con)
df.head()

,Patient_ID,Age,Gender,BMI,Smoking_Status,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Cholesterol_Level,Blood_Sugar_Level,Physical_Activity_Level,Alcohol_Consumption_per_Week,Family_History_Diabetes,Family_History_Heart_Disease,Has_Diabetes,Has_Heart_Disease,Medication_Count,Hospital_Visits_Last_Year,Glucose_Tolerance_Test,Kidney_Function_Score,Has_Chronic_Condition
0,P10000,69,Female,38.3,Former Smoker,116.0,72.0,209.0,135.0,Low,0,No,No,Yes,No,7,4,168.0,77.1,Yes
1,P10001,32,Male,35.6,Non-Smoker,140.0,83.0,216.0,89.0,Moderate,2,No,No,No,No,0,1,89.0,89.7,No
2,P10002,89,Male,14.0,Non-Smoker,107.0,65.0,181.0,123.0,Moderate,0,No,No,No,No,3,0,119.0,84.1,No
3,P10003,78,Female,33.9,Non-Smoker,111.0,84.0,122.0,NaN,Low,0,No,No,No,No,0,0,160.0,85.7,No
4,P10004,38,Female,30.5,Non-Smoker,155.0,93.0,223.0,108.0,Moderate,6,No,No,No,No,1,1,110.0,79.1,No

In [44]:
# Display basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Patient_ID                    10000 non-null  object
 1   Age                           10000 non-null  int64
 2   Gender                        10000 non-null  object
 3   BMI                           10000 non-null  float64
 4   Smoking_Status                10000 non-null  object
 5   Blood_Pressure_Systolic       10000 non-null  float64
 6   Blood_Pressure_Diastolic      10000 non-null  float64
 7   Cholesterol_Level             9500 non-null   float64
 8   Blood_Sugar_Level             9500 non-null   float64
 9   Physical_Activity_Level       10000 non-null  object
 10  Alcohol_Consumption_per_Week  10000 non-null  int64
 11  Family_History_Diabetes       10000 non-null  object
 12  Family_History_Heart_Disease  10000 non-null  object
 13  Has_Diabetes                  10000 non-null  object
 14  Has_Heart_Disease             10000 non-null  object
 15  Medication_Count              10000 non-null  int64
 16  Hospital_Visits_Last_Year     10000 non-null  int64
 17  Glucose_Tolerance_Test        10000 non-null  float64
 18  Kidney_Function_Score         9500 non-null   float64
 19  Has_Chronic_Condition         10000 non-null  object
dtypes: float64(7), int64(4), object(9)
memory usage: 1.5+ MB

In [45]:
# Check duplicates and remove them 
df['Patient_ID'].duplicated().sum()

np.int64(0)

In [46]:
# Check for missing values
df.isna().sum()

Patient_ID                        0
Age                               0
Gender                            0
BMI                               0
Smoking_Status                    0
Blood_Pressure_Systolic           0
Blood_Pressure_Diastolic          0
Cholesterol_Level               500
Blood_Sugar_Level               500
Physical_Activity_Level           0
Alcohol_Consumption_per_Week      0
Family_History_Diabetes           0
Family_History_Heart_Disease      0
Has_Diabetes                      0
Has_Heart_Disease                 0
Medication_Count                  0
Hospital_Visits_Last_Year         0
Glucose_Tolerance_Test            0
Kidney_Function_Score           500
Has_Chronic_Condition             0
dtype: int64

In [47]:
# Fill missing BMI values using Gender median
df['BMI'] = df.groupby('Gender')['BMI'].transform(lambda x: x.fillna(x.median()))

In [58]:
# Create age group by for better data imputation
labels = ['Young','Adult','Middle Age','Senior']
df['Age_Group'] = pd.qcut(df['Age'],4,labels=labels)

In [78]:
# Fill missing Cholesterol,Blood Sugar and Kidney Function values using Gender + Age Group median
df['Cholesterol_Level'] = df.groupby(['Gender','Age_Group'],observed=False)['Cholesterol_Level'].transform(lambda x:x.fillna(x.median()))
df['Blood_Sugar_Level'] = df['Blood_Sugar_Level'].fillna(df.groupby(['Gender','Age_Group'],observed=False)['Blood_Sugar_Level'].transform('median'))
df['Kidney_Function_Score'] = df['Kidney_Function_Score'].fillna(df.groupby(['Gender','Age_Group'],observed=False)['Kidney_Function_Score'].transform('median'))
df.head()

,Patient_ID,Age,Gender,BMI,Smoking_Status,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Cholesterol_Level,Blood_Sugar_Level,Physical_Activity_Level,...,Family_History_Diabetes,Family_History_Heart_Disease,Has_Diabetes,Has_Heart_Disease,Medication_Count,Hospital_Visits_Last_Year,Glucose_Tolerance_Test,Kidney_Function_Score,Has_Chronic_Condition,Age_Group
0,P10000,69,Female,38.3,Former Smoker,116.0,72.0,209.0,135.0,Low,...,No,No,Yes,No,7,4,168.0,77.1,Yes,Middle Age
1,P10001,32,Male,35.6,Non-Smoker,140.0,83.0,216.0,89.0,Moderate,...,No,No,No,No,0,1,89.0,89.7,No,Young Adult
2,P10002,89,Male,14.0,Non-Smoker,107.0,65.0,181.0,123.0,Moderate,...,No,No,No,No,3,0,119.0,84.1,No,Senior
3,P10003,78,Female,33.9,Non-Smoker,111.0,84.0,122.0,99.0,Low,...,No,No,No,No,0,0,160.0,85.7,No,Senior
4,P10004,38,Female,30.5,Non-Smoker,155.0,93.0,223.0,108.0,Moderate,...,No,No,No,No,1,1,110.0,79.1,No,Adult

In [79]:
# Understand numeric distribution
df.describe()

,Age,BMI,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Cholesterol_Level,Blood_Sugar_Level,Alcohol_Consumption_per_Week,Medication_Count,Hospital_Visits_Last_Year,Glucose_Tolerance_Test,Kidney_Function_Score
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,53.539700,27.033820,129.747500,79.950800,200.556500,100.051700,2.819500,2.364600,1.161700,110.171000,84.512925
std,20.757324,5.766543,20.016099,11.952785,43.838559,29.341276,2.474415,1.834176,1.295732,33.645433,9.274663
min,18.000000,6.100000,58.000000,31.000000,35.000000,-19.000000,0.000000,0.000000,0.000000,-21.000000,46.800000
25%,36.000000,23.200000,116.000000,72.000000,172.000000,81.000000,0.000000,1.000000,0.000000,87.000000,78.400000
50%,53.000000,27.000000,130.000000,80.000000,200.000000,100.000000,3.000000,2.000000,1.000000,110.000000,84.800000
75%,72.000000,30.900000,143.000000,88.000000,229.000000,119.000000,4.000000,3.000000,2.000000,133.000000,91.100000
max,89.000000,50.600000,204.000000,124.000000,370.000000,217.000000,13.000000,10.000000,9.000000,229.000000,100.000000

In [82]:
# Converting all column names to lower case
df.columns = df.columns.str.lower()

In [88]:
# Standardizing column name: Converting 'bmi' to uppercase 'BMI'
df.rename(columns={'bmi':'BMI'},inplace=True)

In [90]:
df.head()

,patient_id,age,gender,BMI,smoking_status,blood_pressure_systolic,blood_pressure_diastolic,cholesterol_level,blood_sugar_level,physical_activity_level,...,family_history_diabetes,family_history_heart_disease,has_diabetes,has_heart_disease,medication_count,hospital_visits_last_year,glucose_tolerance_test,kidney_function_score,has_chronic_condition,age_group
0,P10000,69,Female,38.3,Former Smoker,116.0,72.0,209.0,135.0,Low,...,No,No,Yes,No,7,4,168.0,77.1,Yes,Middle Age
1,P10001,32,Male,35.6,Non-Smoker,140.0,83.0,216.0,89.0,Moderate,...,No,No,No,No,0,1,89.0,89.7,No,Young Adult
2,P10002,89,Male,14.0,Non-Smoker,107.0,65.0,181.0,123.0,Moderate,...,No,No,No,No,3,0,119.0,84.1,No,Senior
3,P10003,78,Female,33.9,Non-Smoker,111.0,84.0,122.0,99.0,Low,...,No,No,No,No,0,0,160.0,85.7,No,Senior
4,P10004,38,Female,30.5,Non-Smoker,155.0,93.0,223.0,108.0,Moderate,...,No,No,No,No,1,1,110.0,79.1,No,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P19995,88,Male,22.6,Non-Smoker,149.0,86.0,220.0,114.0,Moderate,...,No,No,No,No,0,0,116.0,78.0,No,Senior
9996,P19996,43,Male,33.6,Non-Smoker,135.0,72.0,109.0,109.0,Low,...,No,No,No,No,1,0,106.0,88.4,No,Adult
9997,P19997,63,Other,29.3,Non-Smoker,145.0,86.0,228.0,113.0,Low,...,No,Yes,No,No,2,1,135.0,93.4,No,Middle Age
9998,P19998,63,Female,29.1,Non-Smoker,80.0,76.0,231.0,141.0,Moderate,...,Yes,No,Yes,No,3,2,142.0,68.6,Yes,Middle Age
9999,P19999,31,Male,27.0,Former Smoker,103.0,55.0,165.0,96.0,Moderate,...,No,Yes,No,No,2,0,106.0,74.8,No,Young Adult

In [95]:
# Upload clened DataFrame to MySQL Database
df.to_sql(name='synthetic_healthcare',
          con =con,
          if_exists='replace',
          index=False)
print('✅ Data successfully uploaded to MySQL (synthetic_healthcare)')

✅ Data successfully uploaded to MySQL (synthetic_healthcare)